### ISSUE TITLE
Minor adjusts in Read.md

### ISSUE THREAD

**Issue by ArthurWalraven** [paulobruno/LearningGbAsm#1]
Rephrasing sugestions:

*__Disclaimer__:
- 1. ~~these codes are~~ __this repository is__ more __of__ a ~~trajectory~~ __record__ of my learning process ~~and not~~ __than__ a set of tutorials for beginners.
- 2. __this repository is not meant as a tutorial for beginners but rather as record of my learning process__.

If you want to ~~know~~ __learn__ how to create your own GB games, the best advice I have for you is to __take a__ look __at__ this really [awesome GB-dev resources](https://github.com/gbdev/awesome-gbdev).*

**Comment by paulobruno** [comment]
Although I used "more" I wouldn't say that it's "more of ... than" because it's not a set of tutorials at all.
The second option is good, but I prefer the original order, first what it is and then what it's not.

I adjusted the text. Thank you for your suggestions.
